name: PureChatExtras
main: jasonwynn10\pce\PureChatExtras
version: 0.1.0
api:
 - 3..0
 - 3.
author: "jasonwynn10"
description: "Modifies the setsuffix and setprefix command from Purechat to allow setting other players tags"
depend:
 - PureChat
